<?php
define('_DB_SERVER_', 'localhost');
define('_DB_NAME_', 'c1vas2');
define('_DB_USER_', 'root');
define('_DB_PASSWD_', '');
#define('_DB_USER_', 'c1vas');
#define('_DB_PASSWD_', 'vas!@#$%^');
define('_DB_PREFIX_', 'ffi_');
define('_MYSQL_ENGINE_', 'InnoDB');
define('_PS_CACHING_SYSTEM_', 'CacheMemcache');
define('_PS_CACHE_ENABLED_', '0');
define('_MEDIA_SERVER_1_', '');
define('_MEDIA_SERVER_2_', '');
define('_MEDIA_SERVER_3_', '');
define('_COOKIE_KEY_', 'favrGId6JrTEvjAX6RL0fdBw9ZgqrwKd392cuucvMpvqb8eGkKdyXPLV');
define('_COOKIE_IV_', '33yC6hIr');
define('_PS_CREATION_DATE_', '2014-08-17');
if (!defined('_PS_VERSION_'))
	define('_PS_VERSION_', '1.6.0.9');
define('_RIJNDAEL_KEY_', 'wa9oALzZj25fg8hbKdqxC6kkTfYJyNGX');
define('_RIJNDAEL_IV_', 'hCQPYwhNcEkh8gted1pHqw==');
